package com.notificationservice.model;

public enum NotificationType {
    MEMBERSHIP_EXPIRY,
    PAYMENT_CONFIRMATION,
    MEMBERSHIP_RENEWAL,
    ATTENDANCE_CHECK_IN,
    ATTENDANCE_CHECK_OUT,
    INACTIVE_USER_REMINDER,
    MONTHLY_ATTENDANCE_SUMMARY,
    WORKOUT_PLAN_ASSIGNED,
    WORKOUT_PLAN_UPDATED,
    DAILY_WORKOUT_REMINDER,
    BIRTHDAY_GREETING,
    PROMOTIONAL,
    TRAINER_ASSIGNED_MEMBER,
    TRAINER_WORKOUT_COMPLETED
}
